language: c

env:
    - SMVERSION=1.0

matrix:
    fast_finish: true
    allow_failures:
        - env: SMVERSION=1.0

before_install:
    - sudo apt-get update

script:
    - ./scripting/PlayerDMG.sp

notifications:
    email: false
